import { BattleOption } from '../models/battle';

export const Attacks: BattleOption[] = [
  {
    name: 'LEFT HOOK',
    attack: 7,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 3,
    speedDescription: 'slow',
    stamina: -10,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'RIGHT HOOK',
    attack: 10,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 4,
    speedDescription: 'slow',
    stamina: -10,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'LEFT JAB',
    attack: 8,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 6,
    speedDescription: 'fast',
    stamina: -10,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'RIGHT JAB',
    attack: 12,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 10,
    speedDescription: 'fast',
    stamina: -10,
    hitChance: 0.95,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'KNEE GROIN',
    attack: 25,
    attackVariance: 5,
    defence: 0,
    defenceVariance: 0,
    speed: 4,
    speedDescription: 'slow',
    stamina: -10,
    hitChance: 0.5,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'HEADBUTT',
    attack: 12,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 10,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: -5,
    healthVariance: 2,
  },
  {
    name: 'KICK',
    attack: 15,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 4,
    speedDescription: 'slow',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'TICKLE',
    attack: 5,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 7,
    speedDescription: 'fast',
    stamina: -5,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'JUDO THROW',
    attack: 55,
    attackVariance: 10,
    defence: 0,
    defenceVariance: 0,
    speed: 1,
    speedDescription: 'slow',
    stamina: -30,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0,
  },
];

export const Defences: BattleOption[] = [
  {
    name: 'DUCK',
    attack: 0,
    attackVariance: 0,
    defence: 45,
    defenceVariance: 15,
    speed: 50,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'DUCK',
    attack: 0,
    attackVariance: 0,
    defence: 45,
    defenceVariance: 15,
    speed: 50,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'DODGE',
    attack: 0,
    attackVariance: 0,
    defence: 80,
    defenceVariance: 15,
    speed: 30,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'DODGE',
    attack: 0,
    attackVariance: 0,
    defence: 80,
    defenceVariance: 15,
    speed: 30,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'DODGE',
    attack: 0,
    attackVariance: 0,
    defence: 80,
    defenceVariance: 15,
    speed: 30,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'SIDE-STEP',
    attack: 0,
    attackVariance: 0,
    defence: 83,
    defenceVariance: 13,
    speed: 35,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'JUMP BACK',
    attack: 0,
    attackVariance: 0,
    defence: 83,
    defenceVariance: 13,
    speed: 25,
    speedDescription: 'very fast',
    stamina: -20,
    hitChance: 0.67,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'JUMP BACK',
    attack: 0,
    attackVariance: 0,
    defence: 83,
    defenceVariance: 13,
    speed: 25,
    speedDescription: 'very fast',
    stamina: -20,
    hitChance: 0.67,
    health: 0,
    healthVariance: 0,
  },
];

export const Wildcards: BattleOption[] = [
  {
    name: 'LAUGH',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 10,
    hitChance: 0.67,
    health: 10,
    healthVariance: 0,
  },
  {
    name: 'LAUGH',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 10,
    hitChance: 0.67,
    health: 10,
    healthVariance: 0,
  },
  {
    name: 'TITTY TWISTER',
    attack: 14,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 40,
    speedDescription: 'very fast',
    stamina: 0,
    hitChance: 0.99,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'CHINESE BURN',
    attack: 16,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 40,
    speedDescription: 'very fast',
    stamina: 0,
    hitChance: 0.99,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'CHINESE BURN',
    attack: 16,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 40,
    speedDescription: 'very fast',
    stamina: 0,
    hitChance: 0.99,
    health: 0,
    healthVariance: 0,
  },
  {
    name: 'TAKE DEEP BREATH',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 30,
    hitChance: 0.9,
    health: 25,
    healthVariance: 0,
  },
  {
    name: 'TAKE DEEP BREATH',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 30,
    hitChance: 0.9,
    health: 25,
    healthVariance: 0,
  },
  {
    name: 'TAKE DEEP BREATH',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 30,
    hitChance: 0.9,
    health: 25,
    healthVariance: 0,
  },
  {
    name: 'EAT CHEESE',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 10,
    hitChance: 0.9,
    health: 50,
    healthVariance: 0,
  },
];

export const DummyAttack = {
  name: 'NOTHING',
  attack: 0,
  attackVariance: 0,
  defence: 0,
  defenceVariance: 0,
  speed: 0,
  speedDescription: 'very slow',
  stamina: 0,
  hitChance: 1,
  health: 0,
  healthVariance: 0,
};
