import { BattleOption } from '../models/battle';

export const Attacks: BattleOption[] = [
  {
    name: 'Left hook',
    attack: 7,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 3,
    speedDescription: 'slow',
    stamina: -10,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Right hook',
    attack: 10,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 4,
    speedDescription: 'slow',
    stamina: -10,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Left jab',
    attack: 8,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 6,
    speedDescription: 'fast',
    stamina: -10,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Right jab',
    attack: 12,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 10,
    speedDescription: 'fast',
    stamina: -10,
    hitChance: 0.95,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Knee groin',
    attack: 25,
    attackVariance: 5,
    defence: 0,
    defenceVariance: 0,
    speed: 4,
    speedDescription: 'slow',
    stamina: -10,
    hitChance: 0.5,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Headbutt',
    attack: 12,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 10,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: -5,
    healthVariance: 2
  },
  {
    name: 'Kick',
    attack: 15,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 4,
    speedDescription: 'slow',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Tickle',
    attack: 5,
    attackVariance: 4,
    defence: 0,
    defenceVariance: 0,
    speed: 7,
    speedDescription: 'fast',
    stamina: -5,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Judo throw',
    attack: 55,
    attackVariance: 10,
    defence: 0,
    defenceVariance: 0,
    speed: 1,
    speedDescription: 'slow',
    stamina: -25,
    hitChance: 0.75,
    health: 0,
    healthVariance: 0
  },
];

export const Defences: BattleOption[] = [
  {
    name: 'Duck',
    attack: 0,
    attackVariance: 0,
    defence: 45,
    defenceVariance: 15,
    speed: 50,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Duck',
    attack: 0,
    attackVariance: 0,
    defence: 45,
    defenceVariance: 15,
    speed: 50,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Dodge',
    attack: 0,
    attackVariance: 0,
    defence: 80,
    defenceVariance: 15,
    speed: 30,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Dodge',
    attack: 0,
    attackVariance: 0,
    defence: 80,
    defenceVariance: 15,
    speed: 30,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Dodge',
    attack: 0,
    attackVariance: 0,
    defence: 80,
    defenceVariance: 15,
    speed: 30,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Side-step',
    attack: 0,
    attackVariance: 0,
    defence: 83,
    defenceVariance: 13,
    speed: 35,
    speedDescription: 'very fast',
    stamina: -15,
    hitChance: 0.85,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Jump back',
    attack: 0,
    attackVariance: 0,
    defence: 83,
    defenceVariance: 13,
    speed: 25,
    speedDescription: 'very fast',
    stamina: -20,
    hitChance: 0.67,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Jump back',
    attack: 0,
    attackVariance: 0,
    defence: 83,
    defenceVariance: 13,
    speed: 25,
    speedDescription: 'very fast',
    stamina: -20,
    hitChance: 0.67,
    health: 0,
    healthVariance: 0
  },
];

export const Wildcards: BattleOption[] = [
  {
    name: 'Laugh',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 10,
    hitChance: 0.67,
    health: 10,
    healthVariance: 0
  },
  {
    name: 'Laugh',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 10,
    hitChance: 0.67,
    health: 10,
    healthVariance: 0
  },
  {
    name: 'Titty twister',
    attack: 14,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 40,
    speedDescription: 'very fast',
    stamina: 0,
    hitChance: 0.99,
    health: 0,
    healthVariance: 0
  },
  {
    name: 'Chinese burn',
    attack: 16,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 40,
    speedDescription: 'very fast',
    stamina: 0,
    hitChance: 0.99,
    health: 0,
    healthVariance: 0
  }, 
  {
    name: 'Chinese burn',
    attack: 16,
    attackVariance: 3,
    defence: 0,
    defenceVariance: 0,
    speed: 40,
    speedDescription: 'very fast',
    stamina: 0,
    hitChance: 0.99,
    health: 0,
    healthVariance: 0
  },  
  {
    name: 'Take deep breath',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 30,
    hitChance: 0.90,
    health: 25,
    healthVariance: 0
  },
  {
    name: 'Take deep breath',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 30,
    hitChance: 0.90,
    health: 25,
    healthVariance: 0
  },
  {
    name: 'Take deep breath',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 30,
    hitChance: 0.90,
    health: 25,
    healthVariance: 0
  },
  {
    name: 'Eat cheese',
    attack: 0,
    attackVariance: 0,
    defence: 0,
    defenceVariance: 0,
    speed: 100,
    speedDescription: 'instant',
    stamina: 10,
    hitChance: 0.90,
    health: 50,
    healthVariance: 0
  },
];