export interface Question extends TextEntry {
  answers: TextEntry[];
}

export interface TextEntry {
  text: string;
  outputText?: string;
  photoLeft?: string;
  photoRight?: string;
  person?: string;
  me: boolean;
  label?: string;
  next?: string;
  take?: string;
  give?: string;
  battle?: string;
  battleAvatar?: string;
}

export interface DialogTree {
  lines: Array<Question | TextEntry>;
}

export const Conversations: { [Key: string]: DialogTree } = {
  Dummy: {
    lines: [],
  },
  Start: {
    lines: [
      {
        text: 'Yawn! I guess it is time to get up.',
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '',
        person: '',
      },
      {
        text: 'Schools out for summer, and my girlfriends parents are away.',
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '',
        person: '',
      },
      {
        text: 'Things are looking good.',
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '',
        person: '',
      },
      {
        text: 'But first, I really need to use the bathroom!',
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '',
        person: '',
      },
    ],
  },
  NoGoDown: {
    lines: [
      {
        text: "It's no use, I need to go to the bathroom first, I'm bursting",
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '',
        person: '',
      },
    ],
  },
  NoExitHome: {
    lines: [
      {
        text: "I can't go outside dressed like this!",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '',
        person: '',
      },
    ],
  },
  Toilet: {
    lines: [
      {
        text: 'Ahh! Much better!',
        me: true,
        photoLeft: '/assets/avatars/player/nude/smile3.png',
        photoRight: '',
        person: '',
      },
    ],
  },
  HelloMum: {
    lines: [
      {
        text: 'Morning, Mum.',
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "Are, good you haven't dressed yet. Planning to go off gallivanting around town again today?",
        me: false,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "I haven't a specific destination in mind.",
        me: true,
        photoLeft: '/assets/avatars/player/nude/smirk.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'You should be concentrating on studying, your future is important you know.',
        me: false,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "It's the summer holidays.",
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'That is no excuse. I want no more of your stupid escapades.',
        me: false,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/annoyed.png',
        person: 'Mother',
      },
      {
        text: "Look, I'm sorry, but I didn't know that Giraffe would eat Mrs. Watson's hat.",
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'Well, you might think twice about going outside. While you where in the bathroom, I emptied your wardrobe.',
        me: false,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/smug.png',
        person: 'Mother',
      },
      {
        text: "I can't walk around in just boxer shorts. I freeze to death.",
        me: true,
        photoLeft: '/assets/avatars/player/nude/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "Here, you can wear this nice summer dress. It will keep you warm, and you won't want to go outside wearing it.",
        me: false,
        photoLeft: '/assets/avatars/player/nude/surprised.png',
        photoRight: '/assets/avatars/mother/delighted.png',
        person: 'Mother',
      },
      {
        text: 'Seriously?',
        me: true,
        photoLeft: '/assets/avatars/player/nude/surprised.png',
        photoRight: '/assets/avatars/mother/delighted2.png',
        person: 'Mother',
      },
      {
        text: 'Nobody else is here. Your father is away on business. With his secretary.',
        me: false,
        photoLeft: '/assets/avatars/player/nude/sad.png',
        photoRight: '/assets/avatars/mother/angry.png',
        person: 'Mother',
      },
      {
        text: "Oh, I'm sure he is very busy!",
        me: true,
        photoLeft: '/assets/avatars/player/nude/laugh.png',
        photoRight: '/assets/avatars/mother/angry.png',
        person: 'Mother',
      },
      {
        text: 'Never mind that. I want to see you dressed before I have to meet Lucy.',
        me: false,
        photoLeft: '/assets/avatars/player/nude/sad.png',
        photoRight: '/assets/avatars/mother/angry.png',
        person: 'Mother',
      },
      {
        text: 'I look like a girl!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/mother/delighted.png',
        person: 'Mother',
      },
      {
        text: 'Well, that is your own fault for not getting a haircut.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'Well, trying to find a barber operating during lockdown was impossible.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "It's time for me to leave. I'll be gone for a couple of days. I'll be staying at Lucy's. We are going dancing in the city.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'The horizontal lambada?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'Cheeky sod. Any more of your nonsense and you will be going to school in a skirt.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'OK. I promise to be a good girl while you are gone.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/smirk.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "Just keep out of trouble. I'm just trying to protect your future.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'If anybody sees me in this, It could well effect my future.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: 'In that case, stay indoors and study. See you later',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/mother/normal.png',
        person: 'Mother',
      },
      {
        text: "As if I'm going anywhere without a good reason.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '',
        person: '',
      },
    ],
  },
  PhoneFromCeo: {
    lines: [
      {
        text: '(Answers phone) Hello?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: '??',
      },
      {
        text: "Is that Marcus? It's Geraldine Glover over at Future Fabrications",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "Yes, that's me. You're the big boss where my father works.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'Yes. We have a problem, and we would normally get your father to fix it, but he has the day off.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "If you are hoping I know where he is, I don't. Also, he told us that he was away on a business trip.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'Is that so? I would confirm that with his assistant, but she is off as well.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/annoyed.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'I take it that is probably against company policy?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "It is most certainly discouraged. I don't know where either of them are today.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "My guess is the're wearing out the bed springs in a cheap hotel on the east coast.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/geraldine/shocked.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'In that case I will be having a serious conversation with the both of them when they return.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/angry.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "If you are going to sack his lazy a**e, then do it on Tuesday. I'm out that evening and won't have to listen to his moaning. Also, my slut of a mother will be back from screwing her lover.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/smile.png',
        photoRight: '/assets/avatars/geraldine/angry.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "You don't have much respect for your parents.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/shocked.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "They disappear for days on end, which I don't mind. Then decide to turn up and micro-manage me to make up for lost time.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/smile.png',
        photoRight: '/assets/avatars/geraldine/angry.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'I am sorry to hear that. However, that is besides the point at the moment.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'Previous conversations with your father suggest you have a talent for getting into things',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "I'm an amateur lock-picker. I may even do it as a future career if I don't can't go to university.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/geraldine/shocked.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'Our latest prototype is in out vault, and we need to show it to a customer this afternoon. However, the lock is jammed.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'You want me to come and look at it?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/delighted.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'Would you kindly?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'Slight problem. My mother has decided to force me to stay indoors by confiscating my clothes. The only thing I have to wear is a girls dress.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/geraldine/oh.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'We are an equal opportunity diversity aware employer. Nobody here will give you any issue with your gender presentation.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/smile.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: 'I have to walk through town to get to you though.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/delighted.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "Did I mention the £300 per hour consultancy fee that I'll pay you, with a minimum callout of 3 hours?",
        me: false,
        photoLeft: '/assets/avatars/player/dress/surprised.png',
        photoRight: '/assets/avatars/geraldine/smirk.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
      {
        text: "I'm on my way.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/smile3.png',
        photoRight: '/assets/avatars/geraldine/delighted2.png',
        person: 'Geraldine Glover, CEO Future Fabrications Inc.',
      },
    ],
  },
  FactoryReception: {
    lines: [],
  },
  WelcomeToGym: {
    lines: [
      {
        text: "Welcome to Ted's Gym.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/gloria/smile.png',
        person: 'Gloria',
      },
      {
        text: 'Hi Gloria',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/gloria/smile.png',
        person: 'Gloria',
      },
      {
        text: "Marcus! Wow, I almost didn't recognise you.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/smile1.png',
        photoRight: '/assets/avatars/gloria/shocked.png',
        person: 'Gloria',
      },
      {
        text: "This isn't my first choice in clothing, but my mother is on a power trip.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/gloria/normal.png',
        person: 'Gloria',
      },
      {
        text: "That women has some funny ideas at times. I'm guessing she's taken all your other clothes?",
        me: false,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/gloria/angry.png',
        person: 'Gloria',
      },
      {
        text: 'Yes. Including my gym kit. Not that I would dare use the changing rooms dressed like this.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/gloria/angry.png',
        person: 'Gloria',
      },
      {
        text: 'I can see how that could cause trouble, especially if you used the ladies.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/smirk.png',
        photoRight: '/assets/avatars/gloria/laugh.png',
        person: 'Gloria',
      },
      {
        text: 'Is Ted about? I think it might be a good idea to do some practice sparring.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/gloria/normal.png',
        person: 'Gloria',
      },
      {
        text: "Sure, he's through on the exercise mat to the right.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/gloria/normal.png',
        person: 'Gloria',
      },
      {
        text: 'Thanks, I have a feeling I might need some self defense skills dressed like this.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/gloria/normal.png',
        person: 'Gloria',
      },
    ],
  },
  Thug1: {
    lines: [
      {
        text: 'What the **** do we ******* have ******* here? Looks like a ******* ******!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Potty mouth Pete',
      },
      {
        text: 'Yippe ki yay, ****** ******!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Potty mouth Pete',
        battle: 'Potty mouth Pete',
        battleAvatar: '/assets/avatars/thug1.png',
      },
    ],
  },
  Thug2: {
    lines: [
      {
        text: 'Ha Ha Ha, Nice dress sissy! If you want to be a girl so bad, perhaps I should kick you in the balls?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Homophobic Henry',
      },
      {
        text: 'You could try!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Homophobic Henry',
        battleAvatar: '/assets/avatars/thug2.png',
        battle: 'Homophobic Henry',
      },
    ],
  },
  Thug3: {
    lines: [
      {
        text: 'Nice dress, Marcie!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Dickish Dave',
        battleAvatar: '/assets/avatars/thug1.png',
        battle: 'Dickish Dave',
      },
      {
        text: 'Touche, Davina!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Dickish Dave',
      },
    ],
  },
  Thug4: {
    lines: [
      {
        text: 'If I said you had a beutiful body, would you hold it against me?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Corny Kevin',
        battleAvatar: '/assets/avatars/thug2.png',
        battle: 'Corny Kevin',
      },
      {
        text: 'A line that corny deserves a damn good thrashing!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Corny Kevin',
      },
    ],
  },
  Thug5: {
    lines: [
      {
        text: 'Well, Hello there! That is a very cute outfit',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Gay Gavin',
        battleAvatar: '/assets/avatars/thug2.png',
        battle: 'Gay Gavin',
      },
      {
        text: 'Urm, thanks, I think',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Gay Gavin',
      },
      {
        text: 'What a beautiful day for rolling in the hay.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Gay Gavin',
        battleAvatar: '/assets/avatars/thug2.png',
        battle: 'Gay Gavin',
      },
      {
        text: "Sorry, you're not my type",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Gay Gavin',
      },
    ],
  },
  Thug6: {
    lines: [
      {
        text: 'Hey Tranny!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Rude Rodney',
        battleAvatar: '/assets/avatars/thug2.png',
        battle: 'Rude Rodney',
      },
      {
        text: 'Hey brain dead!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Rude Rodney',
      },
    ],
  },
  Thug7: {
    lines: [
      {
        text: 'Ha, Ha, I always knew you were a girl!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Thugish Fred',
        battleAvatar: '/assets/avatars/thug1.png',
        battle: 'Thugish Fred',
      },
      {
        text: 'So do you abide by the rule of not hitting girls?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Thugish Fred',
      },
      {
        text: "You're no girl!",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Thugish Fred',
      },
      {
        text: "Do make up your mind. You either think I'm a girl or a boy. Which is it?",
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Thugish Fred',
      },
      {
        text: "Let's see what you fight like!",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Thugish Fred',
      },
    ],
  },
  Thug8: {
    lines: [
      {
        text: 'Marcus, you ****bag! You owe me for that bloody nose!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Bullying Brian',
        battleAvatar: '/assets/avatars/thug2.png',
        battle: 'Bullying Brian',
      },
      {
        text: "Come any closer, and I'll give you two black eye's to match!",
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug2.png',
        person: 'Bullying Brian',
      },
    ],
  },
  Thug9: {
    lines: [
      {
        text: 'Hey Sissy!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Rude Rodney',
        battleAvatar: '/assets/avatars/thug1.png',
        battle: 'Hateful Harold',
      },
      {
        text: 'Hey Moron!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Hateful Harold',
      },
    ],
  },
  Thug10: {
    lines: [
      {
        text: 'That dress makes you look like a five year old!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Rude Rodney',
        battleAvatar: '/assets/avatars/thug1.png',
        battle: 'Goofy Graham',
      },
      {
        text: 'Wow, almost a perfect match for your mental age!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/thug1.png',
        person: 'Goofy Graham',
      },
    ],
  },
  Terrorist1: {
    lines: [
      {
        text: 'Durka Durka Durka, Mohamed, Jihad!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/surprised.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
        battleAvatar: '/assets/avatars/terrorist.png',
        battle: 'Terrorist',
      },
      {
        text: 'Oh ****!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/surprised.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
      },
      {
        text: 'Pew! Pew! Pew! Click! Click! Click!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/ak-47.png',
        person: 'AK-47',
      },
      {
        text: 'Ha, Ha, missed me!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
      },
      {
        text: '****!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/surprised.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
      },
      {
        text: 'Hey, terrorist! Terrorize this!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
      },
    ],
  },
  Terrorist2: {
    lines: [
      {
        text: 'Durka Durka Durka, Mohamed, Jihad!',
        me: false,
        photoLeft: '/assets/avatars/player/dress/surprised.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
        battleAvatar: '/assets/avatars/terrorist.png',
        battle: 'Terrorist',
      },
      {
        text: 'Hey, terrorist! Terrorize this!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/terrorist.png',
        person: 'Terrorist',
      },
    ],
  },
  TankGirl1: {
    lines: [
      {
        text: 'Hey, Trish, are you in there!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Hey Marcus! Or should I be calling you Marcie?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "Sorry, I didn't mean to offend you. I just want to make sure I'm using the right pronouns.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "It's OK. I can see the funny side of my situation. At least among friends.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Whose idea was the dress? Another scatterbrain idea from your mother?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/angry.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "Yes. But honestly, now I've been wearing it for a little while, I'm actually starting to like it.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "I've never been a girly girl, but I do appreciate how light and airy a good summer dress is in hot weather.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "I've been asked to help open the Future Fabrications vault. The lock is jammed. I think I need to cut through the hinges.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "I've seen that thing. I don't think a normal blow torch would cut it. What you need is a cutting charge.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Blow it open?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/surprised.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "Sure. I can make one up for you. All I'll need is some explosives, a length of steel wire, and a case of beer.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "Where do you expect me to get beer from. I'm underage.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'I would have thought the beer would have been the least of your problems.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'There is usually steel rope on the beach. The fishermen use it to pull their boats up.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'The only source of explosives around here would be the quarry.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Be careful in the quarry. I just sold a load of guns to a group of terrorists. They were heading that way to get explosives themselves',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'What the ****!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "Don't worry, they weren't real guns. They were really low powered air rifles. They might sting a bit if you get hit, but won't cause lasting damage.",
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Assuming they can hit anything in the first place',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'You may be able to sneak past them.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: "You don't have any spare camouflage gear do you?",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Sorry, no. None that would fit you at least.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'About the beer?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Tell you what, how about two dozen magic mushrooms instead?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'They grow all around here. You should be able to find some in the woods.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'Great, a fetch quest. That should take up some time.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
    ],
  },
  TankGirl2: {
    lines: [
      {
        text: "Here's your stuff!",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
      {
        text: 'OK. Here is your cutting charge?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/soldier.png',
        person: 'Trish',
      },
    ],
  },
  FutureWelcome: {
    lines: [
      {
        text: 'Welcome to Future Fabrications. Where are world class analysts predict and create the next big thing.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/bailey/smile.png',
        person: 'Bailey',
      },
      {
        text: 'Like the lightweight travel luggage just before Covid?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/bailey/smile.png',
        person: 'Bailey',
      },
      {
        text: 'It will become relevant once unrestricted travel returns.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/bailey/normal.png',
        person: 'Bailey',
      },
      {
        text: "Didn't your analysts predict that Hilary Clinton would be president?",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/bailey/smile.png',
        person: 'Bailey',
      },
      {
        text: 'Nobody would predict an idiot would be elected as president.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/bailey/smug.png',
        person: 'Bailey',
      },
      {
        text: 'So all the Trump second term merchandise you designed was by whom?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/smirk.png',
        photoRight: '/assets/avatars/bailey/normal.png',
        person: 'Bailey',
      },
      {
        text: 'Hey, it was a distinct possibility. Anyway, we designed Biden merchandise as well.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/annoyed.png',
        photoRight: '/assets/avatars/bailey/smile.png',
        person: 'Bailey',
      },
      {
        text: "How's the development of the solar powered spelunking gear coming on?",
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/bailey/angry.png',
        person: 'Bailey',
      },
      {
        text: 'Look here miss! Give me one good reason not to call security and have you removed.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/bailey/angry2.png',
        person: 'Bailey',
      },
      {
        text: 'Your boss, Geraldine, asked me to come and open your vault. I understand the is a problem with it.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/bailey/angry2.png',
        person: 'Bailey',
      },
      {
        text: "You're Marcus!? I was warned a boy might turn up in a dress. I didn't expect you to actually look like a girl!",
        me: false,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/bailey/shocked.png',
        person: 'Bailey',
      },
      {
        text: "I'm not sure if that should be taken as a compliment or not. Perhaps I should speak to your HR department?",
        me: true,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/bailey/angry2.png',
        person: 'Bailey',
      },
      {
        text: 'The is no need for that! Please, head through to the vault. Have a nice day, Miss Marcus.',
        me: false,
        photoLeft: '/assets/avatars/player/dress/laugh.png',
        photoRight: '/assets/avatars/bailey/sad.png',
        person: 'Bailey',
      },
    ],
  },
  Vault1: {
    lines: [
      {
        text: 'Well, can you get this thing open?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'Let me see.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'Holy ****! This is what we call in the business well and truly ****ed.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'I take that as a no then?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'Not necessarily. The lock may be beyond repair, but it may be possible to cut it open. Possibly attack the hinges.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'Very well, if that is the only way in. Is this something you can do, or do I need to call someone else?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: "I'll need to get some equipment. I need to go talk to Trish.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'The weird girl with the tank in her front garden?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: "That's her. She's a military enthusiast. Working on old tanks means she knows how to deal with reinforced armour.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
    ],
  },
  Vault2: {
    lines: [
      {
        text: "OK, I'm ready to open the vault.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'I was expecting some kind of metal cutting torch. What is that?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'A cutting charge.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'Explosives!?',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/shocked.png',
        person: 'Geraldine',
      },
      {
        text: "Not really. It doesn't explode as such, just burn really not really fast. It should melt through the hinges.",
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'Okay, but you better know what you are doing. I assume whoever provided you with that taught you how to use it?',
        me: false,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'OK, that should do it. Stand back.',
        me: true,
        photoLeft: '/assets/avatars/player/dress/normal.png',
        photoRight: '/assets/avatars/geraldine/normal.png',
        person: 'Geraldine',
      },
      {
        text: 'You were only supposed to blow the bloody door off!',
        me: true,
        photoLeft: '/assets/avatars/player/dress/sad.png',
        photoRight: '/assets/avatars/geraldine/angry2.png',
        person: 'Geraldine',
      },
    ],
  },
};
